version: "3.8"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/server/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env
  postgres:
    image: postgres:13-alpine
    env_file: .env
