version: "3.8"

services:
  server:
    image: node:14-alpine
    command: node server/main.js
    volumes:
      - .:/server/
    ports:
      - ${SERVER_PORT}
    env_file: .env
  postgres:
    image: postgres:13-alpine
    env_file: .env
